# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: aserto/api/v1/identity_context.proto, aserto/api/v1/policy_context.proto
# plugin: python-_asertoproto
from dataclasses import dataclass
from typing import List

import _asertoproto
from _asertoproto.grpc.grpclib_server import ServiceBase


class IdentityType(_asertoproto.Enum):
    """
    Identity types, describes the payload type of the identity field inside the
    IdentityContext message.
    """

    # Unknown, value not set, requests will fail with identity type not set
    # error.
    IDENTITY_TYPE_UNKNOWN = 0
    # None, no explicit identity context set, equals anonymous.
    IDENTITY_TYPE_NONE = 1
    # Sub(ject), identity field contains an oAUTH subject.
    IDENTITY_TYPE_SUB = 2
    # JWT, identity field contains a JWT access token.
    IDENTITY_TYPE_JWT = 3


@dataclass(eq=False, repr=False)
class PolicyContext(_asertoproto.Message):
    id: str = _asertoproto.string_field(1)
    path: str = _asertoproto.string_field(2)
    decisions: List[str] = _asertoproto.string_field(3)


@dataclass(eq=False, repr=False)
class IdentityContext(_asertoproto.Message):
    identity: str = _asertoproto.string_field(2)
    type: "IdentityType" = _asertoproto.enum_field(3)
