# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: aserto/api/v1/identity_context.proto, aserto/api/v1/policy_context.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


class IdentityType(betterproto.Enum):
    """
    Identity types, describes the payload type of the identity field inside the
    IdentityContext message.
    """

    # Unknown, value not set, requests will fail with identity type not set
    # error.
    IDENTITY_TYPE_UNKNOWN = 0
    # None, no explicit identity context set, equals anonymous.
    IDENTITY_TYPE_NONE = 1
    # Sub(ject), identity field contains an oAUTH subject.
    IDENTITY_TYPE_SUB = 2
    # JWT, identity field contains a JWT access token.
    IDENTITY_TYPE_JWT = 3


@dataclass(eq=False, repr=False)
class PolicyContext(betterproto.Message):
    id: str = betterproto.string_field(1)
    path: str = betterproto.string_field(2)
    decisions: List[str] = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class IdentityContext(betterproto.Message):
    identity: str = betterproto.string_field(2)
    type: "IdentityType" = betterproto.enum_field(3)
